import { Subject } from '../types';

export const SSC_26_BOOKS: Subject[] = [
  { id: 'bangla_1', name: 'Bangla 1st Paper' },
  { id: 'bangla_2', name: 'Bangla 2nd Paper' },
  { id: 'english_1', name: 'English 1st Paper' },
  { id: 'english_2', name: 'English 2nd Paper' },
  { id: 'math', name: 'Math' },
  { id: 'ict', name: 'Information & Communication Technology' },
  { id: 'chemistry', name: 'Chemistry' },
  { id: 'higher_math', name: 'Higher Math' },
  { id: 'physics', name: 'Physics' },
  { id: 'biology', name: 'Biology' },
  { id: 'bgs', name: 'Bangladesh & Global Studies' },
  { id: 'science', name: 'Science' },
  { id: 'economics', name: 'Economics' },
  { id: 'civics', name: 'Civics & Citizenship' },
  { id: 'history', name: 'History of Bangladesh & World Civilization' },
  { id: 'geo', name: 'Geography & Environment' },
  { id: 'accounting', name: 'Accounting' },
  { id: 'business_ent', name: 'Business Entrepreneurship' },
  { id: 'finance', name: 'Finance & Banking' },
  { id: 'agriculture', name: 'Agriculture Studies' },
  { id: 'home_science', name: 'Home Science' },
  { id: 'arts_crafts', name: 'Arts and Crafts' },
  { id: 'career_edu', name: 'Career Education' },
  { id: 'physical_edu', name: 'Physical Education, Health Science & Sports' },
  { id: 'islam', name: 'Islam Studies' },
  { id: 'hinduism', name: 'Hinduism Studies' },
  { id: 'christianity', name: 'Christianity Studies' },
  { id: 'buddhism', name: 'Buddhism Studies' },
  { id: 'arabic', name: 'Arabic' },
  { id: 'sanskrit', name: 'Sanskrit' },
  { id: 'pali', name: 'Pali' },
  { id: 'music', name: 'Music' },
];