import { Chapter } from "../types";

export const SSC_SYLLABUS: Record<string, Chapter[]> = {
    'bangla_1': [
        { id: 'bangla_1_prose_1', name: 'Shuva (সুভা)' },
        { id: 'bangla_1_prose_2', name: 'Boipora (বইপড়া)' },
        { id: 'bangla_1_prose_3', name: 'Aam-Antir Bhepu (আম-আঁটির ভেঁপু)' },
        { id: 'bangla_1_prose_4', name: 'Manush Muhammad (s.) (মানুষ মুহম্মদ (স.))' },
        { id: 'bangla_1_prose_5', name: 'Nimgaach (নিমগাছ)' },
        { id: 'bangla_1_prose_6', name: 'Shikkha O Manushottwo (শিক্ষা ও মনুষ্যত্ব)' },
        { id: 'bangla_1_prose_7', name: 'Probas Bondhu (প্রবাস বন্ধু)' },
        { id: 'bangla_1_prose_8', name: 'Ekusher Golpo (একুশের গল্প)' },
        { id: 'bangla_1_poetry_1', name: 'Kapotakkha Nad (কপোতা� নদ)' },
        { id: 'bangla_1_poetry_2', name: 'Jibon Binimoy (জীবন িবিনময়)' },
        { id: 'bangla_1_poetry_3', name: 'Umar Farooq (উমর ফারুক)' },
        { id: 'bangla_1_poetry_4', name: 'Seidin Ei Math (েসইদিন এই মাঠ)' },
        { id: 'bangla_1_poetry_5', name: 'Brishti (বৃিষ্ট)' },
        { id: 'bangla_1_poetry_6', name: 'Ami Kono Agontuk Noi (আিম েকােনা আগন্তুক নই)' },
        { id: 'bangla_1_poetry_7', name: 'Tomake Pawar Jonno Hey Swadhinata (েতামােক পাওয়ার জন্য হে স্বাধীনতা)' },
        { id: 'bangla_1_poetry_8', name: 'Boishakh (েবােশখ)' },
        { id: 'bangla_1_novel_1', name: 'Novel: 1971 (উপন্যাস: ১৯৭১)' },
    ],
    'bangla_2': [
        { id: 'bangla_2_ch5', name: 'পরিচ্ছেদ ৫: ধ্বনি ও বর্ণ' },
        { id: 'bangla_2_ch6', name: 'পরিচ্ছেদ ৬: স্বরধ্বনি' },
        { id: 'bangla_2_ch7', name: 'পরিচ্ছেদ ৭: ব্যঞ্জনধ্বনি' },
        { id: 'bangla_2_ch8', name: 'পরিচ্ছেদ ৮: বর্ণের উচ্চারণ' },
        { id: 'bangla_2_ch9', name: 'পরিচ্ছেদ ৯: শব্দ ও পদের গঠন' },
        { id: 'bangla_2_ch10', name: 'পরিচ্ছেদ ১০: উপসর্গ দিয়ে শব্দ গঠন' },
        { id: 'bangla_2_ch11', name: 'পরিচ্ছেদ ১১: প্রত্যয় দিয়ে শব্দ গঠন' },
        { id: 'bangla_2_ch12', name: 'পরিচ্ছেদ ১২: সমাস প্রক্রিয়ায় শব্দ গঠন' },
        { id: 'bangla_2_ch17', name: 'পরিচ্ছেদ ১৭: শব্দের শ্রেণিবিভাগ' },
        { id: 'bangla_2_ch18', name: 'পরিচ্ছেদ ১৮: বিশেষ্য' },
        { id: 'bangla_2_ch19', name: 'পরিচ্ছেদ ১৯: সর্বনাম' },
        { id: 'bangla_2_ch20', name: 'পরিচ্ছেদ ২০: বিশেষণ' },
        { id: 'bangla_2_ch21', name: 'পরিচ্ছেদ ২১: ক্রিয়া' },
        { id: 'bangla_2_ch22', name: 'পরিচ্ছেদ ২২: ক্রিয়া বিশেষণ' },
        { id: 'bangla_2_ch23', name: 'পরিচ্ছেদ ২৩: অনুসর্গ' },
        { id: 'bangla_2_ch24', name: 'পরিচ্ছেদ ২৪: যোজক' },
        { id: 'bangla_2_ch25', name: 'পরিচ্ছেদ ২৫: আবেগ' },
        { id: 'bangla_2_ch31', name: 'পরিচ্ছেদ ৩১: বাক্যের অংশ ও শ্রেণিবিভাগ' },
        { id: 'bangla_2_ch32', name: 'পরিচ্ছেদ ৩২: বাক্যের বর্গ' },
        { id: 'bangla_2_ch33', name: 'পরিচ্ছেদ ৩৩: উদ্দেশ্য ও বিধেয়' },
        { id: 'bangla_2_ch34', name: 'পরিচ্ছেদ ৩৪: সরল, জটিল ও যৌগিক বাক্য' },
        { id: 'bangla_2_ch39', name: 'পরিচ্ছেদ ৩৯: বাগর্থ' },
        { id: 'bangla_2_ch40', name: 'পরিচ্ছেদ ৪০: বাগধারা' },
        { id: 'bangla_2_ch41', name: 'পরিচ্ছেদ ৪১: প্রতিশব্দ' },
        { id: 'bangla_2_ch42', name: 'পরিচ্ছেদ ৪২: বিপরীত শব্দ' },
        { id: 'bangla_2_ch43', name: 'পরিচ্ছেদ ৪৩: শব্দজোড়' },
        { id: 'bangla_2_ch44', name: 'নির্মিতি অংশ: অনুচ্ছেদ' },
        { id: 'bangla_2_ch45', name: 'নির্মিতি অংশ: সারাংশ ও সারমর্ম' },
        { id: 'bangla_2_ch46', name: 'নির্মিতি অংশ: ভাব-সম্প্রসারণ' },
        { id: 'bangla_2_ch47', name: 'নির্মিতি অংশ: চিঠিপত্র' },
        { id: 'bangla_2_ch48', name: 'নির্মিতি অংশ: সংবাদ প্রতিবেদন' },
        { id: 'bangla_2_ch49', name: 'নির্মিতি অংশ: প্রবন্ধ' },
    ],
    'english_1': [
        { id: 'english_1_1', name: 'Unit-1: Sense of Self' },
        { id: 'english_1_2', name: 'Unit-2: Climate Change' },
        { id: 'english_1_3', name: 'Unit-3: Pastimes' },
        { id: 'english_1_6', name: 'Unit-6: Our Neighbours' },
        { id: 'english_1_10', name: 'Unit-10: Dreams' },
        { id: 'english_1_11', name: 'Unit-11: Reading from English Literature' },
        { id: 'english_1_13', name: 'Unit-13: Loneliness' },
        { id: 'english_1_16', name: 'Unit-16: Graffiti' },
        { id: 'english_1_unseen', name: 'Unseen Passages' },
        { id: 'english_1_writing', name: 'Writing Part' },
    ],
    'english_2': [
        { id: 'english_2_1', name: 'Grammar: Adjectives (Articles, Determiners, etc.)' },
        { id: 'english_2_2', name: 'Grammar: Verbs and Tenses' },
        { id: 'english_2_3', name: 'Grammar: Adverb and Adverbials' },
        { id: 'english_2_4', name: 'Grammar: Prepositions' },
        { id: 'english_2_5', name: 'Grammar: Sentences (Types, Questions, Connectors)' },
        { id: 'english_2_writing', name: 'Writing Part (Paragraph, CV, Composition)' },
    ],
    'physics': [
        { id: 'physics_1', name: 'অধ্যায় ১: ভৌত রাশি এবং পরিমাপ' },
        { id: 'physics_2', name: 'অধ্যায় ২: গতি' },
        { id: 'physics_3', name: 'অধ্যায় ৩: বল' },
        { id: 'physics_4', name: 'অধ্যায় ৪: কাজ, ক্ষমতা ও শক্তি' },
        { id: 'physics_7', name: 'অধ্যায় ৭: তরঙ্গ ও শব্দ' },
        { id: 'physics_8', name: 'অধ্যায় ৮: আলোর প্রতিফলন' },
        { id: 'physics_10', name: 'অধ্যায় ১০: স্থির বিদ্যুৎ' },
    ],
    'chemistry': [
        { id: 'chemistry_3', name: 'অধ্যায় ৩: পদার্থের গঠন' },
        { id: 'chemistry_4', name: 'অধ্যায় ৪: পর্যায় সারণি' },
        { id: 'chemistry_5', name: 'অধ্যায় ৫: রাসায়নিক বন্ধন' },
        { id: 'chemistry_6', name: 'অধ্যায় ৬: মোলের ধারণা ও রাসায়নিক গণনা' },
        { id: 'chemistry_7', name: 'অধ্যায় ৭: রাসায়নিক বিক্রিয়া' },
        { id: 'chemistry_11', name: 'অধ্যায় ১১: খনিজ সম্পদ-জীবাশ্ম' },
    ],
    'math': [
        { id: 'math_2', name: 'অধ্যায় ২: সেট ও ফাংশন' },
        { id: 'math_3', name: 'অধ্যায় ৩: বীজগাণিতিক রাশি' },
        { id: 'math_7', name: 'অধ্যায় ৭: ব্যবহারিক জ্যামিতি' },
        { id: 'math_8', name: 'অধ্যায় ৮: বৃত্ত' },
        { id: 'math_9', name: 'অধ্যায় ৯: ত্রিকোণমিতিক অনুপাত' },
        { id: 'math_11', name: 'অধ্যায় ১১: বীজগণিতীয় অনুপাত ও সমানুপাত' },
        { id: 'math_16', name: 'অধ্যায় ১৬: পরিমিতি' },
        { id: 'math_17', name: 'অধ্যায় ১৭: পরিসংখ্যান' },
    ],
    'higher_math': [
        { id: 'higher_math_2', name: 'অধ্যায় ২: বীজগণিতিক রাশি'},
        { id: 'higher_math_7', name: 'অধ্যায় ৭: অসীম ধারা'},
        { id: 'higher_math_10', name: 'অধ্যায় ১০: দ্বিপদী বিস্তৃতি'},
        { id: 'higher_math_8', name: 'অধ্যায় ৮: ত্রিকোণমিতি'},
        { id: 'higher_math_12', name: 'অধ্যায় ১২: সমতলীয় ভেক্টর'},
        { id: 'higher_math_9', name: 'অধ্যায় ৯: সূচকীয় ও লগারিদমীয় ফাংশন'},
        { id: 'higher_math_11', name: 'অধ্যায় ১১: স্থানাঙ্ক জ্যামিতি'},
        { id: 'higher_math_14', name: 'অধ্যায় ১৪: সম্ভাবনা'},
    ],
    'bgs': [
        { id: 'bgs_2', name: 'অধ্যায় ২: স্বাধীন বাংলাদেশ' },
        { id: 'bgs_3', name: 'অধ্যায় ৩: সৌরজগৎ ও ভূমণ্ডল' },
        { id: 'bgs_6', name: 'অধ্যায় ৬: রাষ্ট্র, নাগরিকতা ও আইন' },
        { id: 'bgs_10', name: 'অধ্যায় ১০: জাতীয় সম্পদ ও অর্থনৈতিক ব্যবস্থা' },
        { id: 'bgs_11', name: 'অধ্যায় ১১: অর্থনৈতিক নির্দেশকসমূহ ও বাংলাদেশের অর্থনীতির প্রকৃতি' },
        { id: 'bgs_13', name: 'অধ্যায় ১৩: বাংলাদেশের পরিবার কাঠামো ও সামাজিকীকরণ' },
    ],
    'biology': [
        { id: 'biology_1', name: 'অধ্যায় ১: জীবন পাঠ' },
        { id: 'biology_2', name: 'অধ্যায় ২: জীবকোষ ও টিস্যু' },
        { id: 'biology_3', name: 'অধ্যায় ৩: কোষ বিভাজন' },
        { id: 'biology_4', name: 'অধ্যায় ৪: জীবনীশক্তি' },
        { id: 'biology_11', name: 'অধ্যায় ১১: জীবে প্রজনন' },
        { id: 'biology_12', name: 'অধ্যায় ১২: জীবের বংশগতি ও জৈব অভিব্যক্তি' },
        { id: 'biology_13', name: 'অধ্যায় ১৩: জীবের পরিবেশ' },
    ],
    'ict': [
        { id: 'ict_2', name: 'অধ্যায় ২: কম্পিউটার রক্ষণাবেক্ষণ ও সাইবার নিরাপত্তা' },
        { id: 'ict_4', name: 'অধ্যায় ৪: আমার লেখালেখি ও হিসাব' },
        { id: 'ict_5', name: 'অধ্যায় ৫: মাল্টিমিডিয়া ও গ্রাফিক্স' },
        { id: 'ict_6', name: 'অধ্যায় ৬: প্রোগ্রামিংয়ের মাধ্যমে সমস্যার সমাধান' },
    ],
    'islam': [
        { id: 'islam_1', name: 'অধ্যায় ১: আকাইদ ও নৈতিক জীবন' },
        { id: 'islam_2', name: 'অধ্যায় ২: শরিয়তের উৎস' },
        { id: 'islam_3', name: 'অধ্যায় ৩: ইবাদত' },
        { id: 'islam_4', name: 'অধ্যায় ৪: আখলাক' },
        { id: 'islam_5', name: 'অধ্যায় ৫: আদর্শ জীবনচরিত' },
    ]
};