import { Chapter } from "../types";

export const SSC_SYLLABUS: Record<string, Chapter[]> = {
    'bangla_1': [
        { id: 'bangla_1_prose_1', name: 'Shuva (সুভা)' },
        { id: 'bangla_1_prose_2', name: 'Boipora (বইপড়া)' },
        { id: 'bangla_1_prose_3', name: 'Aam-Antir Bhepu (আম-আঁটির ভেঁপু)' },
        { id: 'bangla_1_prose_4', name: 'Manush Muhammad (s.) (মানুষ মুহম্মদ (স.))' },
        { id: 'bangla_1_prose_5', name: 'Nimgaach (নিমগাছ)' },
        { id: 'bangla_1_prose_6', name: 'Shikkha O Manushottwo (শিক্ষা ও মনুষ্যত্ব)' },
        { id: 'bangla_1_prose_7', name: 'Probas Bondhu (প্রবাস বন্ধু)' },
        { id: 'bangla_1_prose_8', name: 'Ekusher Golpo (একুশের গল্প)' },
        { id: 'bangla_1_poetry_1', name: 'Kapotakkha Nad (কপোতা� নদ)' },
        { id: 'bangla_1_poetry_2', name: 'Jibon Binimoy (জীবন িবিনময়)' },
        { id: 'bangla_1_poetry_3', name: 'Umar Farooq (উমর ফারুক)' },
        { id: 'bangla_1_poetry_4', name: 'Seidin Ei Math (েসইদিন এই মাঠ)' },
        { id: 'bangla_1_poetry_5', name: 'Brishti (বৃিষ্ট)' },
        { id: 'bangla_1_poetry_6', name: 'Ami Kono Agontuk Noi (আিম েকােনা আগন্তুক নই)' },
        { id: 'bangla_1_poetry_7', name: 'Tomake Pawar Jonno Hey Swadhinata (েতামােক পাওয়ার জন্য হে স্বাধীনতা)' },
        { id: 'bangla_1_poetry_8', name: 'Boishakh (েবােশখ)' },
        { id: 'bangla_1_novel_1', name: 'Novel: 1971 (উপন্যাস: ১৯৭১)' },
    ],
    'bangla_2': [
        { id: 'bangla_2_ch5', name: 'Poricched 5: Dhwoni o Borno (পরিচ্ছেদ ৫: ধ্বনি ও বর্ণ)' },
        { id: 'bangla_2_ch6', name: 'Poricched 6: Sworodhoni (পরিচ্ছেদ ৬: স্বরধ্বনি)' },
        { id: 'bangla_2_ch7', name: 'Poricched 7: Byanjondhwoni (পরিচ্ছেদ ৭: ব্যঞ্জনধ্বনি)' },
        { id: 'bangla_2_ch8', name: 'Poricched 8: Borner Uccharon (পরিচ্ছেদ ৮: বর্ণের উচ্চারণ)' },
        { id: 'bangla_2_ch9', name: 'Poricched 9: Shobdo o Poder Gothon (পরিচ্ছেদ ৯: শব্দ ও পদের গঠন)' },
        { id: 'bangla_2_ch10', name: 'Poricched 10: Uposorgo diye Shobdo Gothon (পরিচ্ছেদ ১০: উপসর্গ দিয়ে শব্দ গঠন)' },
        { id: 'bangla_2_ch11', name: 'Poricched 11: Prottoy diye Shobdo Gothon (পরিচ্ছেদ ১১: প্রত্যয় দিয়ে শব্দ গঠন)' },
        { id: 'bangla_2_ch12', name: 'Poricched 12: Shomash prokriyay Shobdo Gothon (পরিচ্ছেদ ১২: সমাস প্রক্রিয়ায় শব্দ গঠন)' },
        { id: 'bangla_2_ch17', name: 'Poricched 17: Shobder Srenibibhag (পরিচ্ছেদ ১৭: শব্দের শ্রেণিবিভাগ)' },
        { id: 'bangla_2_ch18', name: 'Poricched 18: Bisheshyo (পরিচ্ছেদ ১৮: বিশেষ্য)' },
        { id: 'bangla_2_ch19', name: 'Poricched 19: Shorbonam (পরিচ্ছেদ ১৯: সর্বনাম)' },
        { id: 'bangla_2_ch20', name: 'Poricched 20: Bisheshon (পরিচ্ছেদ ২০: বিশেষণ)' },
        { id: 'bangla_2_ch21', name: 'Poricched 21: Kriya (পরিচ্ছেদ ২১: ক্রিয়া)' },
        { id: 'bangla_2_ch22', name: 'Poricched 22: Kriya Bisheshon (পরিচ্ছেদ ২২: ক্রিয়া বিশেষণ)' },
        { id: 'bangla_2_ch23', name: 'Poricched 23: Onusorgo (পরিচ্ছেদ ২৩: অনুসর্গ)' },
        { id: 'bangla_2_ch24', name: 'Poricched 24: Jojok (পরিচ্ছেদ ২৪: যোজক)' },
        { id: 'bangla_2_ch25', name: 'Poricched 25: Abeg (পরিচ্ছেদ ২৫: আবেগ)' },
        { id: 'bangla_2_ch31', name: 'Poricched 31: Bakyer Ongsho o Srenibibhag (পরিচ্ছেদ ৩১: বাক্যের অংশ ও শ্রেণিবিভাগ)' },
        { id: 'bangla_2_ch32', name: 'Poricched 32: Bakyer Borgo (পরিচ্ছেদ ৩২: বাক্যের বর্গ)' },
        { id: 'bangla_2_ch33', name: 'Poricched 33: Uddessho o Bidheyo (পরিচ্ছেদ ৩৩: উদ্দেশ্য ও বিধেয়)' },
        { id: 'bangla_2_ch34', name: 'Poricched 34: Sorol, Jotil o Jougik Bakyo (পরিচ্ছেদ ৩৪: সরল, জটিল ও যৌগিক বাক্য)' },
        { id: 'bangla_2_ch39', name: 'Poricched 39: Bagartho (পরিচ্ছেদ ৩৯: বাগর্থ)' },
        { id: 'bangla_2_ch40', name: 'Poricched 40: Bagdhara (পরিচ্ছেদ ৪০: বাগধারা)' },
        { id: 'bangla_2_ch41', name: 'Poricched 41: Protishobdo (পরিচ্ছেদ ৪১: প্রতিশব্দ)' },
        { id: 'bangla_2_ch42', name: 'Poricched 42: Biporit Shobdo (পরিচ্ছেদ ৪২: বিপরীত শব্দ)' },
        { id: 'bangla_2_ch43', name: 'Poricched 43: Shobdojor (পরিচ্ছেদ ৪৩: শব্দজোড়)' },
        { id: 'bangla_2_ch44', name: 'Nirmiti: Onucched (নির্মিতি অংশ: অনুচ্ছেদ)' },
        { id: 'bangla_2_ch45', name: 'Nirmiti: Sarangsho o Sharmormo (নির্মিতি অংশ: সারাংশ ও সারমর্ম)' },
        { id: 'bangla_2_ch46', name: 'Nirmiti: Bhab-shomprosharon (নির্মিতি অংশ: ভাব-সম্প্রসারণ)' },
        { id: 'bangla_2_ch47', name: 'Nirmiti: Chithipotro (নির্মিতি অংশ: চিঠিপত্র)' },
        { id: 'bangla_2_ch48', name: 'Nirmiti: Shongbad Protibedon (নির্মিতি অংশ: সংবাদ প্রতিবেদন)' },
        { id: 'bangla_2_ch49', name: 'Nirmiti: Probondho (নির্মিতি অংশ: প্রবন্ধ)' },
    ],
    'english_1': [
        { id: 'english_1_1', name: 'Unit-1: Sense of Self' },
        { id: 'english_1_2', name: 'Unit-2: Climate Change' },
        { id: 'english_1_3', name: 'Unit-3: Pastimes' },
        { id: 'english_1_6', name: 'Unit-6: Our Neighbours' },
        { id: 'english_1_10', name: 'Unit-10: Dreams' },
        { id: 'english_1_11', name: 'Unit-11: Reading from English Literature' },
        { id: 'english_1_13', name: 'Unit-13: Loneliness' },
        { id: 'english_1_16', name: 'Unit-16: Graffiti' },
        { id: 'english_1_unseen', name: 'Unseen Passages' },
        { id: 'english_1_writing', name: 'Writing Part' },
    ],
    'english_2': [
        { id: 'english_2_1', name: 'Grammar: Adjectives (Articles, Determiners, etc.)' },
        { id: 'english_2_2', name: 'Grammar: Verbs and Tenses' },
        { id: 'english_2_3', name: 'Grammar: Adverb and Adverbials' },
        { id: 'english_2_4', name: 'Grammar: Prepositions' },
        { id: 'english_2_5', name: 'Grammar: Sentences (Types, Questions, Connectors)' },
        { id: 'english_2_writing', name: 'Writing Part (Paragraph, CV, Composition)' },
    ],
    'physics': [
        { id: 'physics_1', name: 'Chapter 1: Physical Quantities & Measurement (ভৌত রাশি এবং পরিমাপ)' },
        { id: 'physics_2', name: 'Chapter 2: Motion (গতি)' },
        { id: 'physics_3', name: 'Chapter 3: Force (বল)' },
        { id: 'physics_4', name: 'Chapter 4: Work, Power & Energy (কাজ, ক্ষমতা ও শক্তি)' },
        { id: 'physics_7', name: 'Chapter 7: Wave & Sound (তরঙ্গ ও শব্দ)' },
        { id: 'physics_8', name: 'Chapter 8: Reflection of Light (আলোর প্রতিফলন)' },
        { id: 'physics_10', name: 'Chapter 10: Static Electricity (স্থির বিদ্যুৎ)' },
    ],
    'chemistry': [
        { id: 'chemistry_3', name: 'Chapter 3: Structure of Matter (পদার্থের গঠন)' },
        { id: 'chemistry_4', name: 'Chapter 4: Periodic Table (পর্যায় সারণি)' },
        { id: 'chemistry_5', name: 'Chapter 5: Chemical Bonds (রাসায়নিক বন্ধন)' },
        { id: 'chemistry_6', name: 'Chapter 6: Concept of Mole & Chemical Counting (মোলের ধারণা ও রাসায়নিক গণনা)' },
        { id: 'chemistry_7', name: 'Chapter 7: Chemical Reactions (রাসায়নিক বিক্রিয়া)' },
        { id: 'chemistry_11', name: 'Chapter 11: Mineral Resources - Fossils (খনিজ সম্পদ-জীবাশ্ম)' },
    ],
    'math': [
        { id: 'math_2', name: 'Chapter 2: Set & Function (সেট ও ফাংশন)' },
        { id: 'math_3', name: 'Chapter 3: Algebraic Expressions (বীজগাণিতিক রাশি)' },
        { id: 'math_7', name: 'Chapter 7: Practical Geometry (ব্যবহারিক জ্যামিতি)' },
        { id: 'math_8', name: 'Chapter 8: Circle (বৃত্ত)' },
        { id: 'math_9', name: 'Chapter 9: Trigonometric Ratios (ত্রিকোণমিতিক অনুপাত)' },
        { id: 'math_11', name: 'Chapter 11: Algebraic Ratio & Proportion (বীজগণিতীয় অনুপাত ও সমানুপাত)' },
        { id: 'math_16', name: 'Chapter 16: Mensuration (পরিমিতি)' },
        { id: 'math_17', name: 'Chapter 17: Statistics (পরিসংখ্যান)' },
    ],
    'higher_math': [
        { id: 'higher_math_2', name: 'Chapter 2: Algebraic Expressions (বীজগণিতিক রাশি)'},
        { id: 'higher_math_7', name: 'Chapter 7: Infinite Series (অসীম ধারা)'},
        { id: 'higher_math_10', name: 'Chapter 10: Binomial Expansion (দ্বিপদী বিস্তৃতি)'},
        { id: 'higher_math_8', name: 'Chapter 8: Trigonometry (ত্রিকোণমিতি)'},
        { id: 'higher_math_12', name: 'Chapter 12: Planar Vectors (সমতলীয় ভেক্টর)'},
        { id: 'higher_math_9', name: 'Chapter 9: Exponential & Logarithmic Functions (সূচকীয় ও লগারিদমীয় ফাংশন)'},
        { id: 'higher_math_11', name: 'Chapter 11: Coordinate Geometry (স্থানাঙ্ক জ্যামিতি)'},
        { id: 'higher_math_14', name: 'Chapter 14: Probability (সম্ভাবনা)'},
    ],
    'bgs': [
        { id: 'bgs_2', name: 'Chapter 2: Independent Bangladesh (স্বাধীন বাংলাদেশ)' },
        { id: 'bgs_3', name: 'Chapter 3: Solar System & Geosphere (সৌরজগৎ ও ভূমণ্ডল)' },
        { id: 'bgs_6', name: 'Chapter 6: State, Citizenship & Law (রাষ্ট্র, নাগরিকতা ও আইন)' },
        { id: 'bgs_10', name: 'Chapter 10: National Resources & Economic System (জাতীয় সম্পদ ও অর্থনৈতিক ব্যবস্থা)' },
        { id: 'bgs_11', name: 'Chapter 11: Economic Indicators & Nature of Bangladesh Economy (অর্থনৈতিক নির্দেশকসমূহ ও বাংলাদেশের অর্থনীতির প্রকৃতি)' },
        { id: 'bgs_13', name: 'Chapter 13: Family Structure & Socialization in Bangladesh (বাংলাদেশের পরিবার কাঠামো ও সামাজিকীকরণ)' },
    ],
    'biology': [
        { id: 'biology_1', name: 'Chapter 1: Lesson on Life (জীবন পাঠ)' },
        { id: 'biology_2', name: 'Chapter 2: Living Cells & Tissues (জীবকোষ ও টিস্যু)' },
        { id: 'biology_3', name: 'Chapter 3: Cell Division (কোষ বিভাজন)' },
        { id: 'biology_4', name: 'Chapter 4: Bioenergetics (জীবনীশক্তি)' },
        { id: 'biology_11', name: 'Chapter 11: Reproduction in Organisms (জীবে প্রজনন)' },
        { id: 'biology_12', name: 'Chapter 12: Heredity & Evolution (জীবের বংশগতি ও জৈব অভিব্যক্তি)' },
        { id: 'biology_13', name: 'Chapter 13: Environment of Life (জীবের পরিবেশ)' },
    ],
    'ict': [
        { id: 'ict_2', name: 'Chapter 2: Computer Maintenance & Cyber Security (কম্পিউটার রক্ষণাবেক্ষণ ও সাইবার নিরাপত্তা)' },
        { id: 'ict_4', name: 'Chapter 4: My Writing & Calculations (আমার লেখালেখি ও হিসাব)' },
        { id: 'ict_5', name: 'Chapter 5: Multimedia & Graphics (মাল্টিমিডিয়া ও গ্রাফিক্স)' },
        { id: 'ict_6', name: 'Chapter 6: Problem Solving through Programming (প্রোগ্রামিংয়ের মাধ্যমে সমস্যার সমাধান)' },
    ],
    'islam': [
        { id: 'islam_1', name: 'Chapter 1: Aqidah & Moral Life (আকাইদ ও নৈতিক জীবন)' },
        { id: 'islam_2', name: 'Chapter 2: Sources of Shariah (শরিয়তের উৎস)' },
        { id: 'islam_3', name: 'Chapter 3: Ibadah (ইবাদত)' },
        { id: 'islam_4', name: 'Chapter 4: Akhlaq (আখলাক)' },
        { id: 'islam_5', name: 'Chapter 5: Ideal Biographies (আদর্শ জীবনচরিত)' },
    ]
};
